### ISSUE TITLE
tut confusion

### ISSUE THREAD

**Issue by zzz6519003** [bodrovis-learning/messages_dictionary#1]
> What do we want to do next? Obviously, define a new method called has_messages_dictionary. However, we can’t use def for that

but can we use def if we like?

**Comment by bodrovis** [comment]
Now we can't. Method should be defined on the fly and not inside the current module, but inside the receiver (inside the class' context), so we must employ define_method http://ruby-doc.org/core-2.2.2/Module.html#method-i-define_method

**Comment by zzz6519003** [comment]
why should the method be defined on the fly? 🍺

**Comment by bodrovis** [comment]
@zzz6519003 That's a fair question. This module is actually included in some other class, therefore the method must be defined on the fly when the module is included, not before that.

**Comment by zzz6519003** [comment]
that's a fair explanation
