### ISSUE TITLE
tut confusion2

### ISSUE THREAD

**Issue by zzz6519003** [bodrovis-learning/messages_dictionary#2]
>   msg = klass::DICTIONARY_CONF[:msgs].deep_fetch(*key.to_s.split('.')) do

WHATS the * before the `key` used for?

**Comment by bodrovis** [comment]
`*` turns an array into arguments. For example, not `some_method( [1, 2, 3] )`, but `some_method( 1, 2, 3)`

**Comment by bodrovis** [comment]
And also I wanted to note that these issues should not be opened here, as this is the gem's repo - therefore, issues should be related to its functioning. For example, if something is not working, or feature request, or bug report. For general questions you may use comments under the article which I try to constantly monitor.

**Comment by zzz6519003** [comment]
thx man! I'll keep in mind

**Comment by zzz6519003** [comment]
"not some_method( [1, 2, 3] ), but some_method( 1, 2, 3)"

~~can you be a little more specific? XD~~

some_method( *[1, 2, 3])  I see

**Comment by bodrovis** [comment]
True! It turns array to a list of arguments.
